Repository gravitational/gravity, pull requests merged in 2020-04, with the labels that each got.

#1294 SELinux documentation
  build.assets/Makefile
  docs/7.x.yaml
  docs/7.x/installation.md
  docs/7.x/pack.md
  docs/7.x/selinux.md
  lib/install/phases/selinux.go
  lib/schema/constants.go
  lib/schema/manifest.go
  lib/schema/schema.go
  lib/system/selinux/selinux.go
  lib/update/cluster/phases/selinux.go
Labels: selinux

#1340 (7.0) jenkins improvements backport
  Jenkinsfile
  Jenkinsfile.nightly
  build.assets/robotest_run_nightly.sh
  build.assets/robotest_run_suite.sh
Labels: port/7.0

#1344 Update planet.
  Makefile
Labels: port/6.1

#1343 Clarify End of Life for non-LTS releases
  docs/7.x/changelog.md
Labels: kind/docs

#1353 Prevent running some commands from planet.
  tool/gravity/cli/run.go
Labels: port/5.5

#1352 Prevent running some commands from planet.
  tool/gravity/cli/run.go
Labels: port/7.0

#1351 Prevent running some commands from planet.
  tool/gravity/cli/run.go
Labels: port/6.1

#1350 Prevent running some commands from planet.
  tool/gravity/cli/run.go
Labels: port/6.3

#1359 Update planet.
  Makefile
Labels: port/6.3

#1375 Show EULA in CLI installer.
  lib/schema/manifest.go
  lib/schema/schema.go
  tool/gravity/cli/commands.go
  tool/gravity/cli/config.go
  tool/gravity/cli/install.go
  tool/gravity/cli/register.go
Labels: port/6.1

#1379 Show EULA in CLI installer.
  lib/schema/manifest.go
  lib/schema/schema.go
  tool/gravity/cli/commands.go
  tool/gravity/cli/config.go
  tool/gravity/cli/register.go
Labels: port/7.0

#1386 [5.5.x] Add leader change event (#1355)
  Gopkg.lock
  Gopkg.toml
  Makefile
  tool/gravity/cli/history.go
  vendor/github.com/gravitational/satellite/agent/agent.go
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/agent.pb.go
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/agent.proto
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/event.go
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/event.pb.go
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/event.proto
  vendor/github.com/gravitational/satellite/agent/server.go
  vendor/github.com/gravitational/satellite/lib/history/event.go
  vendor/github.com/gravitational/satellite/lib/history/sqlite/constants.go
  vendor/github.com/gravitational/satellite/lib/history/sqlite/event.go
  vendor/github.com/gravitational/satellite/lib/history/sqlite/sqlite.go
  vendor/github.com/gravitational/satellite/lib/history/status.go
  vendor/github.com/gravitational/satellite/lib/history/timeline.go
  vendor/github.com/gravitational/satellite/monitoring/nethealth.go
Labels: port/5.5

#1388 [6.3.x] Add leader change event (#1355)
  Gopkg.lock
  Gopkg.toml
  Makefile
  tool/gravity/cli/history.go
  vendor/github.com/gravitational/satellite/agent/agent.go
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/agent.pb.go
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/agent.proto
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/event.go
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/event.pb.go
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/event.proto
  vendor/github.com/gravitational/satellite/agent/server.go
  vendor/github.com/gravitational/satellite/lib/history/event.go
  vendor/github.com/gravitational/satellite/lib/history/sqlite/constants.go
  vendor/github.com/gravitational/satellite/lib/history/sqlite/event.go
  vendor/github.com/gravitational/satellite/lib/history/sqlite/sqlite.go
  vendor/github.com/gravitational/satellite/lib/history/status.go
  vendor/github.com/gravitational/satellite/lib/history/timeline.go
  vendor/github.com/gravitational/satellite/monitoring/nethealth.go
Labels: port/6.3

#1385 Call status hook after install/upgrade.
  lib/install/phases/app.go
  lib/update/cluster/phases/app.go
Labels: port/6.1

#1363 [5.5.x] add a sub-command to rotate RPC credentials on a cluster
  lib/app/handler/handler_test.go
  lib/app/service/installer.go
  lib/app/service/pull_test.go
  lib/blob/cluster/cluster.go
  lib/blob/cluster/cluster_test.go
  lib/blob/fs/fs.go
  lib/blob/fs/fs_test.go
  lib/blob/handler/blobhandler_test.go
  lib/builder/builder.go
  lib/defaults/defaults.go
  lib/expand/fsm.go
  lib/expand/join.go
  lib/expand/phases/agent.go
  lib/fsm/rpc.go
  lib/httplib/client.go
  lib/install/agent.go
  lib/install/bootstrap.go
  lib/install/flow.go
  lib/install/fsm.go
  lib/install/install.go
  lib/install/phases/app.go
  lib/install/phases/bootstrap.go
  lib/install/phases/pull.go
  lib/localenv/clusterenv.go
  lib/localenv/localenv.go
  lib/ops/opsservice/testhelpers.go
  lib/ops/utils.go
  lib/pack/layerpack/layer_test.go
  lib/pack/localpack/local_test.go
  lib/pack/webpack/webpack_test.go
  lib/process/import.go
  lib/process/process.go
  lib/process/process_test.go
  lib/rpc/tls.go
  lib/storage/keyval/constants.go
  lib/storage/keyval/system.go
  lib/storage/storage.go
  lib/systeminfo/user.go
  lib/update/cluster/phases/bootstrap.go
  lib/update/cluster/phases/election.go
  lib/update/cluster/phases/init.go
  tool/gravity/cli/backup_restore.go
  tool/gravity/cli/commands.go
  tool/gravity/cli/gc.go
  tool/gravity/cli/install.go
  tool/gravity/cli/plan.go
  tool/gravity/cli/register.go
  tool/gravity/cli/rotate.go
  tool/gravity/cli/rpcagent.go
  tool/gravity/cli/run.go
  tool/gravity/cli/site.go
  tool/gravity/cli/update.go
Labels: port/5.5

#1392 Call status hook after install/upgrade.
  lib/install/phases/app.go
  lib/update/cluster/phases/app.go
Labels: port/7.0

#1397 Fix format.
  tool/gravity/cli/status.go
Labels: port/6.1

#1396 Fix format.
  tool/gravity/cli/status.go
Labels: port/7.0

#1394 Fix format.
  tool/gravity/cli/status.go
Labels: port/6.3

#1408 Fix app sync bug.
  tool/gravity/cli/sync.go
Labels: port/5.5

#1406 Correct Assistance Spelling in Web Top Bar 6.3
  web/src/cluster/components/TopBar/RemoteAccess/RemoteAccess.jsx
Labels: ui

#1405 Correct Assistance Spelling in Web Top Bar
  web/src/cluster/components/TopBar/RemoteAccess/RemoteAccess.jsx
Labels: ui

#1413 Add centos 8 to supported distros.
  assets/telekube/resources/app.yaml
Labels: port/7.0

#1418 Update sprig library.
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/Masterminds/goutils/.travis.yml
  vendor/github.com/Masterminds/goutils/CHANGELOG.md
  vendor/github.com/Masterminds/goutils/LICENSE.txt
  vendor/github.com/Masterminds/goutils/README.md
  vendor/github.com/Masterminds/goutils/appveyor.yml
  vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  vendor/github.com/Masterminds/goutils/randomstringutils.go
  vendor/github.com/Masterminds/goutils/stringutils.go
  vendor/github.com/Masterminds/goutils/wordutils.go
  vendor/github.com/Masterminds/sprig/.travis.yml
  vendor/github.com/Masterminds/sprig/CHANGELOG.md
  vendor/github.com/Masterminds/sprig/README.md
  vendor/github.com/Masterminds/sprig/crypto.go
  vendor/github.com/Masterminds/sprig/date.go
  vendor/github.com/Masterminds/sprig/dict.go
  vendor/github.com/Masterminds/sprig/functions.go
  vendor/github.com/Masterminds/sprig/glide.lock
  vendor/github.com/Masterminds/sprig/glide.yaml
  vendor/github.com/Masterminds/sprig/list.go
  vendor/github.com/Masterminds/sprig/network.go
  vendor/github.com/Masterminds/sprig/numeric.go
  vendor/github.com/Masterminds/sprig/strings.go
  vendor/github.com/Masterminds/sprig/url.go
Labels: port/7.0

#1410 reorder election and health checks
  lib/status/status.go
  lib/update/cluster/builder.go
  lib/update/cluster/builder_test.go
  lib/update/cluster/executor.go
  lib/update/cluster/phases/health.go
  lib/update/system/system.go
Labels: port/5.5, port/6.1, port/7.0

#1434 Fix some join token issues
  lib/ops/opsservice/configure.go
  lib/ops/opsservice/install.go
  lib/process/teleport.go
Labels: port/6.3

#1440 Update vendored helm to 2.15.2.
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/helm/pkg/chartutil/load.go
  vendor/k8s.io/helm/pkg/chartutil/testdata/bad_symlink/LICENSE
  vendor/k8s.io/helm/pkg/chartutil/testdata/bad_symlink/dnull
  vendor/k8s.io/helm/pkg/chartutil/testdata/frobnitz_symlinks/LICENSE
  vendor/k8s.io/helm/pkg/chartutil/values.go
  vendor/k8s.io/helm/pkg/sympath/walk.go
Labels: port/7.0

#1439 bump planet
  Makefile
Labels: port/5.5

#1444 Fix join token issues.
  lib/ops/opsservice/configure.go
  lib/process/teleport.go
Labels: port/6.1

#1443 Fix join token issues.
  lib/ops/opsservice/configure.go
  lib/process/teleport.go
Labels: port/5.5

#1446 Add internal commands to fix teleport tokens.
  lib/loc/loc.go
  lib/process/import.go
  tool/gravity/cli/commands.go
  tool/gravity/cli/register.go
  tool/gravity/cli/run.go
  tool/gravity/cli/teleport.go
Labels: port/5.5

#1449 [7.0.x] Add leader change event (#1355)
  Gopkg.lock
  Gopkg.toml
  Makefile
  tool/gravity/cli/history.go
  vendor/github.com/gravitational/satellite/agent/agent.go
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/agent.pb.go
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/agent.proto
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/event.go
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/event.pb.go
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/event.proto
  vendor/github.com/gravitational/satellite/agent/server.go
  vendor/github.com/gravitational/satellite/lib/history/event.go
  vendor/github.com/gravitational/satellite/lib/history/sqlite/constants.go
  vendor/github.com/gravitational/satellite/lib/history/sqlite/event.go
  vendor/github.com/gravitational/satellite/lib/history/sqlite/sqlite.go
  vendor/github.com/gravitational/satellite/lib/history/status.go
  vendor/github.com/gravitational/satellite/lib/history/timeline.go
  vendor/github.com/gravitational/satellite/monitoring/nethealth.go
Labels: port/7.0

#1455 Update helm to 2.15.2.
  Makefile
Labels: port/7.0

#1453 Fix join token issue.
  lib/ops/opsservice/configure.go
  lib/ops/opsservice/install.go
  lib/process/teleport.go
Labels: port/7.0

#1464 [5.5.x] Disable nethealth check
  Makefile
  build.assets/robotest_run_nightly.sh
  build.assets/robotest_run_suite.sh
Labels: port/5.5

#1465 [6.1.x] Disable nethealth check
  Makefile
  build.assets/robotest_run_nightly.sh
  build.assets/robotest_run_suite.sh
Labels: port/6.1

#1466 [6.3.x] Disable nethealth check
  Makefile
Labels: port/6.3

#1467 [7.0.x] Disable nethealth check
  Makefile
  build.assets/robotest_run_nightly.sh
  build.assets/robotest_run_suite.sh
Labels: port/7.0
