Repository gravitational/gravity, pull requests merged in 2020-05, with the labels that each got.

#1477 Add Teleport node status checks
  lib/expand/builder.go
  lib/expand/fsmspec.go
  lib/expand/join.go
  lib/expand/phases/wait.go
  lib/expand/plan_test.go
  lib/ops/ops.go
  lib/ops/opsservice/service.go
  lib/status/status.go
  tool/gravity/cli/status.go
Labels: port/5.5

#1498 [5.5.x] Separate critical and warning probes
  lib/constants/constants.go
  lib/status/status.go
  tool/gravity/cli/status.go
Labels: port/5.5

#1499 [6.1.x] Separate critical and warning probes
  lib/constants/constants.go
  lib/status/status.go
  tool/gravity/cli/status.go
Labels: port/6.1

#1504 (6.3) Fix issue with trusted cluster role map
  lib/storage/trustedcluster.go
  lib/storage/trustedcluster_test.go
Labels: port/6.3

#1512 Update DNS application hook
  assets/dns-app/hooks/entrypoint.sh
Labels: kind/enhancement

#1545 Fix wordpress cluster manifest link
  docs/7.x/quickstart.md
  docs/7.x/terraform.md
Labels: kind/docs

#1538 Docs Update hub install flag instructions to use --hub-advertise-addr
  docs/7.x/hub.md
Labels: kind/docs

#1537 [7.0.x] service stop conditions
  lib/expand/join.go
  lib/install/client/client.go
  lib/install/client/install.go
  lib/install/install.go
  lib/install/server/server.go
Labels: port/6.3

#1570 [5.5.x] Collect status history in gravity report (#1520)
  lib/ops/opsservice/report.go
  lib/report/report.go
  lib/report/timeline.go
  lib/status/timeline.go
  tool/gravity/cli/history.go
Labels: port/5.5

#1572 [7.0.x] Collect status history in gravity report (#1520)
  lib/ops/opsservice/report.go
  lib/report/report.go
  lib/report/timeline.go
  lib/status/timeline.go
  tool/gravity/cli/history.go
Labels: port/7.0

#1559 Initial Gravity Example dir and robot-shop-app cluster image
  examples/README.md
  examples/robot-shop-app/README.md
  examples/robot-shop-app/resources/app.yaml
  examples/robot-shop-app/resources/charts/robot-shop/Chart.yaml
  examples/robot-shop-app/resources/charts/robot-shop/README.md
  examples/robot-shop-app/resources/charts/robot-shop/templates/cart-deployment.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/cart-service.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/catalogue-deployment.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/catalogue-service.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/clusterrole.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/clusterrolebinding.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/dispatch-deployment.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/dispatch-service.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/mongodb-deployment.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/mongodb-service.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/mysql-deployment.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/mysql-service.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/payment-deployment.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/payment-service.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/podsecuritypolicy.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/rabbitmq-deployment.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/rabbitmq-service.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/ratings-deployment.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/ratings-service.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/redis-service.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/redis-statefulset.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/serviceaccount.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/shipping-deployment.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/shipping-service.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/user-deployment.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/user-service.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/web-deployment.yaml
  examples/robot-shop-app/resources/charts/robot-shop/templates/web-service.yaml
  examples/robot-shop-app/resources/charts/robot-shop/values.yaml
  examples/robot-shop-app/resources/install.yaml
  examples/robot-shop-app/resources/upgrade.yaml
  examples/robot-shop-app/robotshop.png
Labels: example

#1542 [7.0.x] expand resume
  build.assets/robotest_run_suite.sh
  lib/expand/join.go
  lib/expand/phases/etcd.go
  lib/install/client/install.go
  lib/install/client/resume.go
  lib/install/proto/client.go
  lib/install/utils.go
  lib/ops/opsservice/agents.go
  lib/storage/storage.go
Labels: port/6.3

#1580 [5.5.x] Nethealth patch
  Gopkg.lock
  Gopkg.toml
  Makefile
  vendor/github.com/gravitational/satellite/agent/health/health.go
  vendor/github.com/gravitational/satellite/monitoring/nethealth.go
  vendor/github.com/gravitational/satellite/monitoring/timedrift.go
Labels: port/5.5

#1612 [7.0.x] Nethealth patch
  Gopkg.lock
  Gopkg.toml
  Makefile
  vendor/github.com/gravitational/satellite/lib/history/sqlite/constants.go
  vendor/github.com/gravitational/satellite/monitoring/nethealth.go
Labels: port/7.0

#1387 [6.1.x] Add leader change event (#1355)
  Gopkg.lock
  Gopkg.toml
  tool/gravity/cli/history.go
  vendor/github.com/gravitational/satellite/agent/agent.go
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/agent.pb.go
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/agent.proto
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/event.go
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/event.pb.go
  vendor/github.com/gravitational/satellite/agent/proto/agentpb/event.proto
  vendor/github.com/gravitational/satellite/agent/server.go
  vendor/github.com/gravitational/satellite/lib/history/event.go
  vendor/github.com/gravitational/satellite/lib/history/sqlite/constants.go
  vendor/github.com/gravitational/satellite/lib/history/sqlite/event.go
  vendor/github.com/gravitational/satellite/lib/history/sqlite/sqlite.go
  vendor/github.com/gravitational/satellite/lib/history/status.go
  vendor/github.com/gravitational/satellite/lib/history/timeline.go
  vendor/github.com/gravitational/satellite/monitoring/nethealth.go
Labels: port/6.1
