Repository gravitational/gravity, pull requests merged in 2021-08, with the labels that each got.

#2629 [5.5] Update CODEOWNERS
  .github/CODEOWNERS
Labels: port/5.5

#2626 [8.0] Update CODEOWNERS
  .github/CODEOWNERS
Labels: port/8.0

#2623 [8.0.x] Update tiller registry
  assets/tiller-app/Makefile
  assets/tiller-app/resources/resources.yaml
  web/src/cluster/components/K8s/Deployments/Deployments.story.js
  web/src/cluster/components/K8s/Pods/Pods.story.js
Labels: regression, build/tooling

#2621 [7.0] Update tiller registry
  assets/tiller-app/Makefile
  assets/tiller-app/resources/resources.yaml
  web/src/cluster/components/K8s/Deployments/Deployments.story.js
  web/src/cluster/components/K8s/Pods/Pods.story.js
Labels: regression, build/tooling, port/7.0
